### ISSUE TITLE
(BUG) calling a page with Maps creates "fe_typo3_user" Cookie

### ISSUE THREAD

**Issue by MartinHotmann** [mhirdes/go_maps_ext#73] opened 2020-04-27 21:20 UTC
As this creates the Cookie this will block the ability to cache the page as soon as it creates this cookie.
As far as I know this cookie is not needed so I would like it not to be set.

My setup:

TYPO3: 10.4.0
go_maps_ext: 4.0.0-dev

**Comment by MartinH0** [comment] 2020-06-09 02:21
@mhirdes is there any update on this? Or explanation why this cookie i set?
For me and my understanding everything about this EXT in teh frontend can be statically so there would be no need for setting this cookie as is makes the Page uncachable.

**Comment by mhirdes** [comment] 2020-06-19 09:27
Hi. I can't reproduce this.

**Comment by MartinH0** [comment] 2020-11-02 21:54
I will try to provide a video or very clear instructions and a proof that this is happening. I have tried that back some monthes ago several times and could see a cookie set for this extension.
But I also cant see the v4.0.0-dev branch here on GitHub anymore somehow

**Comment by mhirdes** [comment] 2020-12-29 16:30
Still need feedback here.

**Comment by MartinHotmann** [comment] 2021-01-04 19:16
Sorry for the late reply.
It defenitely was a `fe_typo3_user` cookie.


I run some more tests and found out that this is not related to your extension, but to the form which also in included on the page. 

I still use: `4.0.0-dev` on TYPO3 `v10.4.12` seems to work fine.

**Comment by mhirdes** [comment] 2021-04-01 10:07
Ok, if this problem pop ups again, you can reopen this issue. For now I'll close it.

**Closed by mhirdes** 2021-04-01 10:07 UTC
Labels: needs feedback
